### PR TITLE
fix: 936 embedding cell count

### LINKED ISSUE #936: BUG: Bug 1: Selected cells discrepancy between umap and spatial
Context:
Slack: https://czi-sci.slack.com/archives/C0247APK621/p1711647089759669

Couple things to iron out towards Visium support. They may be caused by an embedding having null values for some of the obs.
1. `umap` shows `4992 of 4992 cells`, but only 4113 cells are included in the `obsm[‘X_umap’]`.

Toggling triggers/resolves

Repro: start on umap (bug1) --> spatial --> umap --> spatial (bug2 + bug3)

Example: https://cellxgene.cziscience.com/e/a3b219d6-6606-4d82-82fe-fe76f3889c3c.cxg/

Bug 1:

Current:  umap shows 4992 of 4992
Fix: Should show 4113 of 4113

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94ebac97112b0933bab33a118aee0b69c171f5b4/Screen%20Recording%202024-03-28%20at%2010.19.33%E2%80%AFAM.mov)

### PR DESCRIPTION
**Pull request by tihuan**
Fix #936 

1. `doInitialDataLoad` action now choose the initial layout by checking if the dataset's preferred `default_embedding` is available or not and fall back to picking the best layout given the available layouts
2. This resolves two bugs:
    1. On page load, we no longer get the layout flickering caused by the layoutChoice first setting a fallback layout, and then switching to the dataset preferred layout
    2. Fixes #936
3. Extract a new selector `selectAvailableLayouts ` to reuse

https://github.com/chanzuckerberg/single-cell-explorer/assets/6309723/ac978673-82d4-4b72-be01-a41593d2b2da

### CODE REVIEW

File: client/src/actions/index.ts [hunk 1]
```diff
@@ -233,17 +235,26 @@ const doInitialDataLoad = (): ((
...
-      }
+      const finalLayout = availableLayouts.includes(defaultLayout)
+        ? defaultLayout
+        : fallbackLayout;
+
+      dispatch({
+        type: "initial data load complete",
+        isCellGuideCxg,
+        layoutChoice: finalLayout,
+      });
```
Comment (tihuan) [inline client/src/actions/index.ts:250]: when we dispatch this action, we send both `isCellGuideCxg` and `layoutChoice`

File: client/src/actions/index.ts [hunk 2]
```diff
@@ -233,17 +235,26 @@ const doInitialDataLoad = (): ((
...
+
+      /**
+       * (thuang): This dispatch is necessary to ensure that we get the right cell
+       * count when the page is first loaded.
+       * BUG: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/936
+       */
+      dispatch(embActions.layoutChoiceAction(finalLayout));
```
Comment (tihuan) [inline client/src/actions/index.ts:257]: we still dispatch this action in order to get the correct crossFilter, etc.

File: client/src/components/embedding/index.tsx [hunk 3]
```diff
@@ -27,20 +27,12 @@ type EmbeddingState = any;
   crossfilter: state.obsCrossfilter,
   imageUnderlay: state.imageUnderlay,
 }))
-// eslint-disable-next-line @typescript-eslint/ban-types --- FIXME: disabled temporarily on migrate to TS.
-class Embedding extends React.PureComponent<{}, EmbeddingState> {
-  // eslint-disable-next-line @typescript-eslint/ban-types --- FIXME: disabled temporarily on migrate to TS.
-  constructor(props: {}) {
```
Comment (tihuan) [inline client/src/components/embedding/index.tsx:33]: remove unnecessary ctor per linter

File: client/src/components/embedding/index.tsx [hunk 4]
```diff
@@ -27,20 +27,12 @@ type EmbeddingState = any;
...
-    super(props);
-    this.state = {};
-  }
-
+class Embedding extends React.PureComponent<Props> {
```
Comment (tihuan) [inline client/src/components/embedding/index.tsx:30]: just type cleanup in this file

File: client/src/reducers/layoutChoice.ts [hunk 5]
```diff
@@ -10,23 +10,8 @@ about commonly used names.  Preferentially, pick in the following order:
...
-import { EmbeddingSchema, Schema } from "../common/types/schema";
-
-function bestDefaultLayout(layouts: Array<string>): string {
-  const preferredNames = ["umap", "tsne", "pca"];
-  const idx = preferredNames.findIndex((name) => layouts.indexOf(name) !== -1);
-  if (idx !== -1) return preferredNames[idx];
-  return layouts[0];
-}
-
-function setToDefaultLayout(schema: Schema): LayoutChoiceState {
```
Comment (tihuan) [inline client/src/reducers/layoutChoice.ts:22]: this function is now split out into `selectAvailableLayouts` and `getCurrentLayout` for reusability

File: client/src/selectors/annoMatrix.ts [hunk 6]
```diff
@@ -1,17 +1,17 @@
 /* App dependencies */
+import AnnoMatrix from "../annoMatrix/annoMatrix";
 import { AnnotationColumnSchema } from "../common/types/schema";
-import { RootState } from "../reducers";
+import { type RootState } from "../reducers";
 
-// eslint-disable-next-line @typescript-eslint/no-explicit-any --- update typings once annoMatrix reducer state is typed.
-export const selectAnnoMatrix = (state: RootState): any => state.annoMatrix;
```
Comment (tihuan) [inline client/src/selectors/annoMatrix.ts:6]: type cleanup

File: client/src/selectors/annoMatrix.ts [hunk 7]
```diff
@@ -20,3 +20,8 @@ export const selectIsUserStateDirty = (state: any): boolean => {
     )
   );
 };
+
+export function selectSchema(state: RootState) {
```
Comment (tihuan) [inline client/src/selectors/annoMatrix.ts:24]: new selector to get annoMatrix.schema

**Review by seve — APPROVED** [review]

File: client/src/actions/index.ts [hunk 8]
```diff
@@ -233,17 +235,26 @@ const doInitialDataLoad = (): ((
...
+      dispatch({
+        type: "initial data load complete",
+        isCellGuideCxg,
+        layoutChoice: finalLayout,
+      });
+
+      /**
+       * (thuang): This dispatch is necessary to ensure that we get the right cell
+       * count when the page is first loaded.
+       * BUG: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-explorer/936
```
[the remark this answers is not in the document]
Comment (tihuan) [reply client/src/actions/index.ts:255]: Oh thank you! I'll use https://github.com/chanzuckerberg/single-cell-explorer/issues/936
