### PR TITLE
fix: 1022 Fix color by category bug

### LINKED ISSUE #1022: bug(P0): Explorer Page Goes Blank When Color By Filters Are Changed
## 
From Corinn S:
I'm experiencing an issue in prod when I go from one category to another to change the color scale in Explorer. The first time I click on the droplet button, the color scale shows up fine. However, when I try to change the category, the page goes completely blank, but only after expanding the initial category.

Steps to recreate issue:
choose initial category for color scale
expand that category
try to choose the second category

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0c1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a550ed51731b694596c7b2933a79707afe305674/Screen%20Recording%202024-07-05%20at%2010.29.22%E2%80%AFAM%20%281%29.mov)

### PR DESCRIPTION
**Pull request by tihuan**
fixes #1022 

Source of bug:

https://github.com/chanzuckerberg/single-cell-explorer/pull/977#discussion_r1667138687

### CODE REVIEW

**Review by kaloster — APPROVED** [review]

File: client/src/components/categorical/category/index.tsx [hunk 1]
```diff
@@ -313,6 +311,7 @@ class Category extends React.PureComponent<CategoryProps> {
           <Async.Fulfilled persist>
             {(asyncProps: CategoryAsyncProps) => {
               const {
+                colorAccessor,
```
Comment (tihuan) [inline client/src/components/categorical/category/index.tsx:314]: https://github.com/chanzuckerberg/single-cell-explorer/pull/977#discussion_r1667138687
